services:
  - type: web
    name: skauttrebic2022-strapi
    env: node
    plan: starter
    region: frankfurt
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: rsync -a public/ /data/public/ && yarn start
    rootDir: apps/strapi
    healthCheckPath: /_health
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 14.20.0
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_FILENAME
        value: /data/strapi.db
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ALLOW_CREATE_SUPER_ADMIN_STRAPI_USER
        value: false
      - key: FRONTEND_URL
        value: https://new.skauttrebic.cz
