services:
  - type: web
    name: skauttrebic2022-strapi
    env: node
    plan: starter
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: rsync -a public/ /data/public/ && yarn start
    rootDir: apps/strapi
    healthCheckPath: /_health
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /data/strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
