import type { NextPage } from 'next'  
import styles from '../styles/Home.module.css'
import Link from "next/link"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      {/*<Head>*/}
      {/*  <title>Create Next App</title>*/}
      {/*  <meta name="description" content="Generated by create next app" />*/}
      {/*  <link rel="icon" href="/favicon.ico" />*/}
      {/*</Head>*/}

      <main>
        hello
          <Link href={'/testik'}>testik</Link>
      </main>

      <footer>
       footer
      </footer>
    </div>
  )
}

export default Home
